const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin Function', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin Function', async function() {
    await driver.get("http://localhost:3000/addGames/mainfeed")
    await driver.manage().window().setRect({ width: 1269, height: 1032 })
    await driver.findElement(By.linkText("Mainfeed")).click()
    await driver.findElement(By.linkText("Games")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Nick")
    await driver.findElement(By.css(".inner-wrap")).click()
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("dumbylol")
    await driver.findElement(By.name("Sign Up")).click()
    await driver.findElement(By.linkText("Mainfeed")).click()
    await driver.findElement(By.linkText("Games")).click()
    await driver.findElement(By.linkText("My Profile")).click()
    await driver.findElement(By.linkText("Mainfeed")).click()
    await driver.findElement(By.linkText("Nick")).click()
    await driver.findElement(By.linkText("Mainfeed")).click()
    await driver.findElement(By.linkText("Nick")).click()
    await driver.findElement(By.linkText("Mainfeed")).click()
    await driver.findElement(By.linkText("Dumbledore")).click()
    await driver.findElement(By.linkText("My Profile")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.linkText("Admin Panel Access")).click()
    await driver.findElement(By.name("gameName")).click()
    await driver.findElement(By.name("gameName")).sendKeys("Hollow Knight")
    await driver.findElement(By.name("gameGenre")).click()
    await driver.findElement(By.name("gameGenre")).sendKeys("Adventure")
    await driver.findElement(By.name("gamePlatform")).click()
    await driver.findElement(By.name("gamePlatform")).sendKeys("PC PS4 XBO Switch")
    await driver.findElement(By.name("gameReleaseDate")).click()
    await driver.findElement(By.name("gameReleaseDate")).sendKeys("2017")
    await driver.findElement(By.id("reviewText")).click()
    await driver.findElement(By.name("gameImage")).click()
    await driver.findElement(By.name("gameImage")).sendKeys("C:\\fakepath\\hollowknight.jpg")
    await driver.findElement(By.id("reviewText")).click()
    await driver.findElement(By.id("reviewText")).sendKeys("Utterly awesome game about being a little bug in a big world. ")
    await driver.findElement(By.name("Sign Up")).click()
    await driver.findElement(By.linkText("Games")).click()
  })
})
